[project]
name = "ask-ragu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Raguram", email = "raguram4123@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
ask-ragu = "ask_ragu:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"
